#------------------------------------------------------
# Environment specific variables 
#------------------------------------------------------

# Global variables
environment: "devops" # ----------------------------------------------------- prod
appd_app_name: "PMGateway-7761-PROD" # ----------------------------------------------------- prod

# RDS
engine: "postgres"
engine_version: "12.3"
skip_final_snapshot: "true"
instance_class: "db.t2.micro"