#------------------------------------------------------
# Application specific variables 
#------------------------------------------------------

# Application name
application_name: "aboyanov" # ----------------------------------------------------- prod
